name: DeathSwap
main: co.kolya.deathswap.DeathSwap
version: 1.0.0
author: Kolya Venturi
commands:
   deathswap:
      description: Create, start, and join DeathSwap games
      usage: /deathswap [create|join|start] [gameID]
   ds:
      description: Create, start, and join DeathSwap games
      usage: /ds [create|join|start] [gameID]